DROP TABLE IF EXISTS YogiBear.Highscores;

CREATE DATABASE IF NOT exists YogiBear;


CREATE TABLE IF NOT EXISTS Highscores(
  ID  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Score INT NOT NULL
);
USE YogiBear;